_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.8
            "5": 0.19.2
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.2
            "13": windows-amd64
epochs:
    value: 250
learning_rate:
    value: 0.001
model:
    value: ATT_13
